<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-04T09:50:07 IST" name="Suite" finished-at="2021-10-04T09:51:46 IST" duration-ms="98354">
    <groups>
    </groups>
    <test started-at="2021-10-04T09:50:07 IST" name="Test" finished-at="2021-10-04T09:51:46 IST" duration-ms="98354">
      <class name="oct2_ExtentReporting.ContactUsTestcases">
        <test-method is-config="true" signature="testbefore()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:50:07 IST" name="testbefore" finished-at="2021-10-04T09:50:08 IST" duration-ms="223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testbefore -->
        <test-method is-config="true" signature="navigateBrowser()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:50:08 IST" name="navigateBrowser" finished-at="2021-10-04T09:50:11 IST" duration-ms="3341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateBrowser -->
        <test-method is-config="true" signature="beforemethod()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:50:11 IST" name="beforemethod" finished-at="2021-10-04T09:50:36 IST" duration-ms="24622" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method signature="contactUsTest001()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:50:36 IST" name="contactUsTest001" finished-at="2021-10-04T09:50:54 IST" duration-ms="18559" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest001 -->
        <test-method is-config="true" signature="aftermethod()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:50:54 IST" name="aftermethod" finished-at="2021-10-04T09:51:03 IST" duration-ms="9359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method is-config="true" signature="beforemethod()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:51:03 IST" name="beforemethod" finished-at="2021-10-04T09:51:19 IST" duration-ms="15296" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method signature="contactUsTest002()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:51:19 IST" name="contactUsTest002" finished-at="2021-10-04T09:51:36 IST" duration-ms="17196" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at oct2_ExtentReporting.ContactUsTestcases.contactUsTest002(ContactUsTestcases.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest002 -->
        <test-method is-config="true" signature="aftermethod()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:51:36 IST" name="aftermethod" finished-at="2021-10-04T09:51:45 IST" duration-ms="9054" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method signature="contactUsTest003()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:51:45 IST" name="contactUsTest003" finished-at="2021-10-04T09:51:45 IST" depends-on-methods="oct2_ExtentReporting.ContactUsTestcases.contactUsTest002" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ContactUsTestcases.contactUsTest003()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ContactUsTestcases.contactUsTest003()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest003 -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:51:45 IST" name="afterClass" finished-at="2021-10-04T09:51:46 IST" duration-ms="596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="testafter()[pri:0, instance:oct2_ExtentReporting.ContactUsTestcases@1da2cb77]" started-at="2021-10-04T09:51:46 IST" name="testafter" finished-at="2021-10-04T09:51:46 IST" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testafter -->
      </class> <!-- oct2_ExtentReporting.ContactUsTestcases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
